
---
alertmanager_external_url: "http://{{ prometheus_domain }}:9093"
alertmanager_slack_api_url: "https://{{ slack_domain }}"
alertmanager_receivers:
- name: slack
  slack_configs:
  - send_resolved: true
    channel: '#infra-health-alerts'
alertmanager_route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  receiver: slack