name: Validate Terraform plans

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
          
      - name: Checkout
        uses: actions/checkout@v2

      - name: Check syntax
        run: |
          pwd
          ls terraform/| while read file
          do
            if [[ -d $file ]]; then
              terraform fmt -check "$file"
            fi
          done
